import {
	ChartSpline,
	Check,
	ChevronsUpDown,
	Eclipse,
	Hash,
	Home,
	Languages,
	LayoutGrid,
	List,
	ListOrdered,
	ListPlus,
	Loader2,
	LogOut,
	MessageCircleQuestionMark,
	Moon,
	Plus,
	Rows4,
	Settings2,
	Sparkle,
	Star,
	Sun,
	Table2,
	User,
	Warehouse,
} from 'lucide-react'
import React from 'react'

type IconProps = React.HTMLAttributes<SVGElement>

export const Icons = {
	moon: (props: IconProps) => <Moon {...props} />,
	sun: (props: IconProps) => <Sun {...props} />,
	sparkle: (props: IconProps) => <Sparkle {...props} />,
	plus: (props: IconProps) => <Plus {...props} />,
	home: (props: IconProps) => <Home {...props} />,
	settings: (props: IconProps) => <Settings2 {...props} />,
	languages: (props: IconProps) => <Languages {...props} />,
	help: (props: IconProps) => <MessageCircleQuestionMark {...props} />,
	logout: (props: IconProps) => <LogOut {...props} />,
	user: (props: IconProps) => <User {...props} />,
	upDownChevron: (props: IconProps) => <ChevronsUpDown {...props} />,
	eclipse: (props: IconProps) => <Eclipse {...props} />,
	warehouse: (props: IconProps) => <Warehouse {...props} />,
	check: (props: IconProps) => <Check {...props} />,
	loader: (props: IconProps) => <Loader2 {...props} />,
	logo: (props: IconProps) => <ListPlus {...props} />,
	table: (props: IconProps) => <Table2 {...props} />,
	star: (props: IconProps) => <Star {...props} />,
	hashtag: (props: IconProps) => <Hash {...props} />,
	list: (props: IconProps) => <ListOrdered {...props} />,
	rows: (props: IconProps) => <Rows4 {...props} />,
	chartspline: (props: IconProps) => <ChartSpline {...props} />,
	grid: (props: IconProps) => <LayoutGrid {...props} />,
	listlayout: (props: IconProps) => <List {...props} />,
}
